version = "Two"

edition = "2021"
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
match_block_trailing_comma = true
max_width = 115
use_field_init_shorthand = true
# use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true

# Unstable features below
comment_width = 120
imports_layout = "HorizontalVertical"
unstable_features = true
wrap_comments = true

single_line_if_else_max_width = 120
